# Screen size
WIDTH = 400
HEIGHT = 440

# Game field start position and size
GAME_FIELD_Y_START = 40
GAME_FIELD_WIDTH = 400
GAME_FIELD_HEIGHT = 360

# Game states
STATE_PLAYER_MAKES_TURN = 'STATE_PLAYER_MAKES_TURN'
STATE_WAITING_FOR_BOT_TO_TURN = 'STATE_WAITING_FOR_BOT_TO_TURN'
STATE_BOT_MAKES_TURN = 'STATE_BOT_MAKES_TURN'
STATE_WAITING_FOR_GAME_OVER = 'STATE_WAITING_FOR_GAME_OVER'
STATE_GAME_OVER = 'STATE_GAME_OVER'
