# Screen size
WIDTH = 400
HEIGHT = 360

# Game states
STATE_PLAYER_MAKES_TURN = 'STATE_PLAYER_MAKES_TURN'
STATE_WAITING_FOR_BOT_TO_TURN = 'STATE_WAITING_FOR_BOT_TO_TURN'
STATE_BOT_MAKES_TURN = 'STATE_BOT_MAKES_TURN'
STATE_WAITING_FOR_GAME_OVER = 'STATE_WAITING_FOR_GAME_OVER'
STATE_GAME_OVER = 'STATE_GAME_OVER'
